Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BDVendaDireta.Models;

namespace BDVendaDireta.Controllers
{
    public class UsuariosController : Controller
    {
        private BDVendaDiretaContect db = new BDVendaDiretaContect();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "Email,Senha")] Usuario usuario)
        {
            if (Session["UsuarioId"] != null)
            {
                return RedirectToAction("Index", "Produtos");
            }
                Usuario usuarioEncontrado = db.Usuario.Where(u => u.Email == usuario.Email).FirstOrDefault();
            if (usuarioEncontrado != null && usuarioEncontrado.Senha.Equals(usuario.Senha))
            {
                ViewBag.Error = "";
                Session["UsuarioId"] = usuarioEncontrado.UsuarioId;
                Session["UsuarioNome"] = usuarioEncontrado.Nome.ToString();
                Session["UsuarioReceita"] = usuarioEncontrado.Receita.ToString();
                return RedirectToAction("Index", "Produtos");
            }
            else
            {
                ViewBag.Error = "Não foi possível realizar o login. Tente novamente.";
            }
            return View(usuario);
        }

        public ActionResult Logout()
        {
            Session["UsuarioId"] = null;
            Session["UsuarioNome"] = null;
            Session["UsuarioReceita"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Create()
        {
            if (Session["UsuarioId"] != null)
            {
                return RedirectToAction("Index", "Produtos");
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UsuarioId,Nome,Email,Senha")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Receita = 0;
                db.Usuario.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Login");
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bárbara Rossalli</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BDVendaDireta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
         
            <div class="navbar-header navbar-right">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["UsuarioId"] != null)
                {
                    <span class="text-info">
                      Olá,  @Session["UsuarioNome"].ToString() -   @Session["UsuarioReceita"].ToString() | 
                    </span>
           
                    @Html.ActionLink("[SAIR]", "Logout", "Usuarios")
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bárbara Rossalli</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>