Models/Produto.cs
namespace BDVendaDireta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Produto")]
    public partial class Produto
    {
        public int ProdutoId { get; set; }

        public int UsuarioId { get; set; }

        [Required]
        [StringLength(200)]
        public string Nome { get; set; }

        public decimal Preco { get; set; }

        public bool Vendido { get; set; }

        public virtual Usuario Usuario { get; set; }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BDVendaDireta.Models;

namespace BDVendaDireta.Controllers
{
    public class ProdutosController : Controller
    {
        private BDVendaDiretaContect db = new BDVendaDiretaContect();

        public ActionResult Index()
        {
            if (Session["UsuarioId"] != null)
            {
                IQueryable<Produto> produto = db.Produto.Where(p => p.Vendido == false);
                return View(produto.ToList());
            }
            return RedirectToAction("Login", "Usuarios");
        }

        public ActionResult Details(int? id)
        {
            if (Session["UsuarioId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Produto produto = db.Produto.Find(id);
                if (produto == null)
                {
                    return HttpNotFound();
                }
                return View(produto);
            }
            return RedirectToAction("Login", "Usuarios");
        }

        public ActionResult Create()
        {
            if (Session["UsuarioId"] != null)
            {
                ViewBag.UsuarioId = new SelectList(db.Usuario, "UsuarioId", "Nome");
                return View();
            }
            return RedirectToAction("Login", "Usuarios");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdutoId,UsuarioId,Nome,Preco,Vendido")] Produto produto)
        {
            if (ModelState.IsValid)
            {
                produto.Vendido = false;
                produto.UsuarioId = Convert.ToInt32(Session["UsuarioId"]);
                db.Produto.Add(produto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UsuarioId = new SelectList(db.Usuario, "UsuarioId", "Nome", produto.UsuarioId);
            return View(produto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details([Bind(Include = "ProdutoId,UsuarioId,Nome,Preco,Vendido")] Produto produto)
        { 
                Produto vendido = db.Produto.Find(produto.ProdutoId);
                vendido.Vendido = true;
                Usuario usuario = db.Usuario.Find(vendido.UsuarioId);
                usuario.Receita = usuario.Receita + vendido.Preco;
                db.SaveChanges();
                Session["UsuarioReceita"] = usuario.Receita;
                return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}
;

Views/Produtos/Create.cshtml
@model BDVendaDireta.Models.Produto

@{
    ViewBag.Title = "Create";
}

<h2>Novo Produto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Produtos/Details.cshtml
@model BDVendaDireta.Models.Produto

@{
    ViewBag.Title = "Details";
}

<h2>Confirmar Compra</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
     

        @Html.HiddenFor(model=> model.ProdutoId)
        <div class="form-group">
            <b> @Html.DisplayNameFor(model => model.Nome) :
            </b>
        
                @Html.DisplayFor(model => model.Nome)
        </div>

        <div class="form-group">
            <b>
                @Html.DisplayNameFor(model => model.Preco) :
            </b>

                @Html.DisplayFor(model => model.Preco)

</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar Compra" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Produtos/Index.cshtml
@model IEnumerable<BDVendaDireta.Models.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Produtos</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.ActionLink("Comprar", "Details", new { id=item.ProdutoId }) 
        </td>
    </tr>
}

</table>

<div class="col-md-4">
    <div class="btn btn-default ">
        @Html.ActionLink("Adicionar", "Create", "Produtos")
    </div>
</div>